### ISSUE TITLE
Make an export script to nexus

### ISSUE THREAD

**Issue by LinguList** [lexibank/crossandean#13]
This can be done in two ways:

1. using pyedictor in a Makefile in the folder `edictor` (please no script folders in the folder `raw`, `raw` is for the data, not for scripts, unless scripts are to modify the data)
2. using a command like `cldfbench crossandean.make_nexus`

**Comment by LinguList** [comment]
This command needs to take the CLDF data and create the nexus file from there.

**Comment by LinguList** [comment]
@Tarotis, should I provide an example, which you could use for this?

**Comment by Tarotis** [comment]
We do have a short script that fetches the data and filters some concepts and doculects, using the subset-utility of wordlists. I like the idea of including a `make_nexus` command though, and will adapt the script accordingly.

**Comment by LinguList** [comment]
An early example is here: https://github.com/lexibank/chenhmongmien/

**Comment by LinguList** [comment]
Please check the setup.py script that offers additional lines. The command folder is called "crossandeancommands".

**Comment by LinguList** [comment]
Nexus file should be written to a folder `output`, I guess, or `nexus`.
