### ISSUE TITLE
Fix code points of modified graphemes

### ISSUE THREAD

**Issue by Tarotis** [lexibank/crossandean#15]
# Found 12 generated graphemes
| Grapheme | Grapheme-UC | BIPA | BIPA-UC | Modified | Segments | Graphemes | Count |
|:-----------|:---------------------|:-------|:---------------------|:-----------|:-------------|:------------|--------:|
| ue | U+0075 U+0065 | ue | U+0075 U+0065 | | b ue l ɛ | vwelë. | 1 |
| uiː | U+0075 U+0069 U+02d0 | uiː | U+0075 U+0069 U+02d0 | | uiː j aː n i | ui:yá:ni | 1 |
| ʁ’ | U+0281 U+2019 | ʁʼ | U+0281 U+02bc | * | h i s ʁ’ u n | hisγ'un | 1 |
| ua | U+0075 U+0061 | ua | U+0075 U+0061 | | k ua | cua | 2 |
| sʰ | U+0073 U+02b0 | sʰ | U+0073 U+02b0 | | oː χ sʰ a | ó:χsʰá | 2 |
| ie | U+0069 U+0065 | ie | U+0069 U+0065 | | v ie n t o | viento | 3 |
| oi | U+006f U+0069 | oi | U+006f U+0069 | | k oi ʎ u r | coyllur | 9 |
| s̺ | U+0073 U+033a | s̺ | U+0073 U+033a | | s̺ i p a s̺ | ʃipas | 18 |
| r̝ | U+0072 U+031d | r̝ | U+0072 U+031d | | r̝ u k u | řuku | 20 |
| ui | U+0075 U+0069 | ui | U+0075 U+0069 | | h u tʃ ui | huchuy | 39 |
| au | U+0061 U+0075 | au | U+0061 U+0075 | | m au k a | mawka | 113 |
| ai | U+0061 U+0069 | ai | U+0061 U+0069 | | h a n ai | hanay | 351 |
# Found 13 modified graphemes
| Grapheme | Grapheme-UC | BIPA | BIPA-UC | Segments | Graphemes | Count |
|:-----------|:---------------------|:-------|:---------------------|:---------------------|:-------------|--------:|
| q’ | U+0071 U+2019 | qʼ | U+0071 U+02bc | s u q’ u + n i | suq’uni | 1 |
| ds | U+0064 U+0073 | dz | U+0064 U+007a | k uː ds i | kú:dži | 1 |
| t’ | U+0074 U+2019 | tʼ | U+0074 U+02bc | t’ iː r a | t’í:r̂a | 1 |
| p’ | U+0070 U+2019 | pʼ | U+0070 U+02bc | p’ a e k e | p’aéke | 2 |
| ts’ | U+0074 U+0073 U+2019 | tsʼ | U+0074 U+0073 U+02bc | ts’ a: t + k a t n i | ts’á:t-kátni | 3 |
| k’ | U+006b U+2019 | kʼ | U+006b U+02bc | k’ e l j u | k’élyu | 6 |
| tʃ’ | U+0074 U+0283 U+2019 | tʃʼ | U+0074 U+0283 U+02bc | tʃ’ u s a | ch’usa | 9 |
| o: | U+006f U+003a | oː | U+006f U+02d0 | k a: l o: | ka:lo: | 10 |
| ʈʂ’ | U+0288 U+0282 U+2019 | ʈʂʼ | U+0288 U+0282 U+02bc | a s ʈʂ’ a | asĉ'a | 10 |
| u: | U+0075 U+003a | uː | U+0075 U+02d0 | p a: k u: | pá:ku: | 13 |
| e: | U+0065 U+003a | eː | U+0065 U+02d0 | ʃ e: k u | še:ku | 14 |
| i: | U+0069 U+003a | iː | U+0069 U+02d0 | t s i: | tsi: | 22 |
| a: | U+0061 U+003a | aː | U+0061 U+02d0 | k a: l o: | ka:lo: | 40 |
# Found 3 slashed graphemes
| Grapheme | Grapheme-UC | BIPA | BIPA-UC | Segments | Graphemes | Count |
|:-----------|:--------------|:-------|:----------|:------------------------|:------------|--------:|
| r/j | U+0072 | j | U+006a | t i j/r a + r/j i + n a | tirayina | 1 |
| j/r | U+006a | r | U+0072 | t i j/r a + r/j i + n a | tirayina | 1 |
| tʃ/k | U+0074 U+0283 | k | U+006b | k u tʃ/k u tʃ u | kukuchi | 1 |

**Comment by LinguList** [comment]
Essential things are U+2019 vs. U+02bc, where one should use the latter, etc.

**Comment by Tarotis** [comment]
I rerun the command and this is the most recent output:

# Found 12 generated graphemes
| Grapheme | Grapheme-UC | BIPA | BIPA-UC | Modified | Segments | Graphemes | Count |
|:-----------|:---------------------|:-------|:---------------------|:-----------|:-------------|:------------|--------:|
| ue | U+0075 U+0065 | ue | U+0075 U+0065 | | b ue l ɛ | vwelë. | 1 |
| uiː | U+0075 U+0069 U+02d0 | uiː | U+0075 U+0069 U+02d0 | | uiː j aː n i | ui:yá:ni | 1 |
| ʁʼ | U+0281 U+02bc | ʁʼ | U+0281 U+02bc | | h i s ʁʼ u n | hisγ'un | 1 |
| ua | U+0075 U+0061 | ua | U+0075 U+0061 | | k ua | cua | 2 |
| sʰ | U+0073 U+02b0 | sʰ | U+0073 U+02b0 | | oː χ sʰ a | ó:χsʰá | 2 |
| ie | U+0069 U+0065 | ie | U+0069 U+0065 | | v ie n t o | viento | 3 |
| oi | U+006f U+0069 | oi | U+006f U+0069 | | k oi ʎ u r | coyllur | 9 |
| s̺ | U+0073 U+033a | s̺ | U+0073 U+033a | | s̺ i p a s̺ | ʃipas | 18 |
| r̝ | U+0072 U+031d | r̝ | U+0072 U+031d | | r̝ u k u | řuku | 20 |
| ui | U+0075 U+0069 | ui | U+0075 U+0069 | | h u tʃ ui | huchuy | 39 |
| au | U+0061 U+0075 | au | U+0061 U+0075 | | m au k a | mawka | 113 |
| ai | U+0061 U+0069 | ai | U+0061 U+0069 | | h a n ai | hanay | 351 |
# Found 3 slashed graphemes
| Grapheme | Grapheme-UC | BIPA | BIPA-UC | Segments | Graphemes | Count |
|:-----------|:--------------|:-------|:----------|:------------------------|:------------|--------:|
| r/j | U+0072 | j | U+006a | t i j/r a + r/j i + n a | tirayina | 1 |
| j/r | U+006a | r | U+0072 | t i j/r a + r/j i + n a | tirayina | 1 |
| tʃ/k | U+0074 U+0283 | k | U+006b | k u tʃ/k u tʃ u | kukuchi | 1 |

The change will be implemented in #16

**Comment by LinguList** [comment]
Are you sure about the tʃ/k etc. cases?

**Comment by LinguList** [comment]
And note that cases like `ua` are usually better rendered as `w a`, or in slashed notation as `u/w a`, as the glides in front of a vowel are usually more salient, that is, they have more consonantal weight than after the vowel, in my experience. But I agree it is tedious to separate those consistently.

**Comment by Tarotis** [comment]
We have explicit commentaries in those cases that `tʃ` and `k` are alternating in these cases. Should we add two separate entries instead?

**Comment by LinguList** [comment]
What does alternating mean? Like German "pfanne" vs. "fanne", depending 
on the situation and the speaker or the whims of the speaker, or 
alternating based on phonological context?

**Comment by Tarotis** [comment]
This is not specified in the original source.

**Comment by LinguList** [comment]
One can leave it as is, but computationally, it will always be a k. If it is three entries, one could add a Variant field to the forms.csv and add the form with the affricate there.

**Comment by Tarotis** [comment]
I stand corrected:  I went to the original sources and adopted the changes. This will be fixed in the next PR (#16 ).
